// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbgxyfrxmorlgdgytlui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5iZ3h5ZnJ4bW9ybGdkZ3l0bHVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MDE1MDksImV4cCI6MjA2MjA3NzUwOX0.LZVmGVhiTeTTIesuUOwCHcomOV6nsQBgTnn7uDVGdho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);