// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcdgpphpdzjgqcskyxup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjZGdwcGhwZHpqZ3Fjc2t5eHVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Mjc3NTgsImV4cCI6MjA2MjAwMzc1OH0.nOb_cXYtsQE87kFUq7mYkIfWOR5KehX99QuwpXB_gec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);